spring:
  application.name: INFO
  datasource:
    url: jdbc:mysql://localhost:3306/info
    username: info_back
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret-key: info-application-secret-key-for-development-must-over-256-bit
  access-token:
    expired-time-sec: 360 # 1 hour (60 * 60)
  refresh-token:
    expired-time-sec: 2592000 # 30 days (30 * 24 * 60 * 60)

logging:
  level:
    com.example.INFO.user: DEBUG
